### ISSUE TITLE
--help / -h should return errorcode 0

### ISSUE THREAD

**Issue by tseemann** [dnbaker/bonsai#11]
Your -h seem to be 'errors' and return 1 not 0

When -h sepcificed should go to stdout too, not stderr.

**Comment by dnbaker** [comment]
I think that log messages (IE, those not meant to be consumed by downstream tools) should be emitted to stderr, as they are meant to be read by humans. I consider help menus to be among them.

Similarly, I think that an exit status should be EXIT_FAILURE for a -h/--help so that a pipeline doesn't incorrectly believe that it has correctly executed the program if an -h was specified by accident.

**Comment by tseemann** [comment]
I disagree on both points :)
But you're the boss.
